apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: cluster-policy
spec:
  namespaces:
    - "*"
  allowIncomingLinks: true
  allowedOutgoingLinksHostnames: ["172\\.18\\..*$"]
  allowedExposedResources:
    - "deployment/backend"
    - "deployment/echo"
  allowedServices:
    - "backend"
    - "echo"